### ISSUE TITLE
UI Enhancements

### ISSUE THREAD

**Issue by JacobSamro** [aroliant/hash2.dev#11]
### TODO 

- [x] Improve the Navigation Bar
- [x] Show the Stargazers somewhere on site
- [x] Show we are Open Source
- [x] Hide the Logo on Mobile Screens
- [x] Improve Buttons
- [x] Improve Card Design

## Modal Improvements
- [x] Align the Modal Close Button
- [x] Improve textarea outline
- [x] Increase the width of the Modal

**Comment by JacobSamro** [comment]
Closing in favour of #26
